#ifndef __BBCAT_ADM_REGISTER__
#define __BBCAT_ADM_REGISTER__

#include <bbcat-base/misc.h>

BBC_AUDIOTOOLBOX_START
// source file automatically generated by autotools and cmake
extern bool bbcat_register_bbcat_adm();
BBC_AUDIOTOOLBOX_END

#endif
